export const ProductsList = [
  {
    id: 1,
    src: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    productName: "iphone",
    price: 10000,
    quantity: 1,
  },
  {
    id: 2,
    src: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    productName: "iphone 13",
    price: 23000,
    quantity: 30,
  },
  {
    id: 3,
    src: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    productName: "blackberry",
    price: 20,
    quantity: 0,
  },
  {
    id: 4,
    src: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    productName: "oppo",
    price: 5000,
    quantity: 20,
  },
  {
    id: 5,
    src: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    productName: "Xaomi",
    price: 2500,
    quantity: 40,
  },
  {
    id: 6,
    src: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    productName: "laptop",
    price: 16000,
    quantity: 30,
  },
  {
    id: 7,
    src: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    productName: "laptop 2",
    price: 20000,
    quantity: 15,
  },
  {
    id: 8,
    src: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    productName: "laptop 3",
    price: 30000,
    quantity: 10,
  },
  {
    id: 9,
    src: "https://i.dummyjson.com/data/products/33/thumbnail.jpg",
    productName: "iphone",
    price: 10000,
    quantity: 30,
  },
  {
    id: 10,
    src: "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
    productName: "t-shirt",
    price: 500,
    quantity: 30,
  },
];
